Add statistics feature
AY2223S2-CS2103T-W14-1/tp pull request #141
Opened 2023-03-23 10:48 UTC by RubyNguyen07

I added the statistics box, which includes top three projects due soon (that has yet to be "done") and a pie chart showing project status with corresponding percentages

2023-03-23 14:12 UTC, immanuelhume requested changes
overall looks good and works well :+1: but we probably need to discuss some details

2023-03-23 14:12 UTC, immanuelhume commented on src/main/resources/view/StatisticsBox.fxml
> +        <PieChart fx:id="deadlinePieChart" legendSide="RIGHT" title="Deadline statistics" startAngle="90"/>
Hmm it's not exactly showing deadline statistics tho, how about a title like "Progress Overview"?

2023-03-23 14:12 UTC, immanuelhume commented on src/main/java/mycelium/mycelium/logic/Logic.java
> +    HashMap<String, Long> getProjectStatistics();
Best if we can add some javadocs for these to describe what they do, especially what the return values mean

2023-03-23 14:12 UTC, immanuelhume commented on src/main/java/mycelium/mycelium/model/ModelManager.java
> +    }
Think we'll need to discuss further on how to determine this list :thinking:. Since now overdue projects are also returned

2023-03-23 14:12 UTC, immanuelhume commented on src/main/java/mycelium/mycelium/model/ModelManager.java
> +        projectStatusWithCount.put("In Progress", inProgress);
For this filter, it's probably better to just check against the enum directly, i.e. something like
```java
project.getStatus() == ProjectStatus.NOT_STARTED
```
instead of calling toString

2023-03-24 05:43 UTC, RubyNguyen07 commented on src/main/java/mycelium/mycelium/model/ModelManager.java
> +        projectStatusWithCount.put("In Progress", inProgress);
sounds better, i have fixed accordingly

2023-03-24 05:44 UTC, RubyNguyen07 commented on src/main/java/mycelium/mycelium/model/ModelManager.java
> +    }
For now, I set due soon projects to be within this or next week (overdue projects will not be counted)

2023-03-24 05:44 UTC, RubyNguyen07 commented on src/main/java/mycelium/mycelium/logic/Logic.java
> +    HashMap<String, Long> getProjectStatistics();
Ok added!

2023-03-24 05:44 UTC, RubyNguyen07 commented on src/main/resources/view/StatisticsBox.fxml
> +        <PieChart fx:id="deadlinePieChart" legendSide="RIGHT" title="Deadline statistics" startAngle="90"/>
Yep, sounds better!

2023-03-24 05:44 UTC, RubyNguyen07 commented on src/main/resources/view/StatisticsBox.fxml
> +        <Label text="Due soon projects" alignment="CENTER" styleClass="chart-title"/>
I changed the name accordingly

2023-03-24 06:35 UTC, immanuelhume commented on src/main/java/mycelium/mycelium/model/ModelManager.java
> +                sortedProjectList.size() >= 3 ? 3 : sortedProjectList.size()));
do u think it's better to just return all instead of limiting to 3? coz what if there are more than 3 projects with the exact same deadline

2023-03-24 06:38 UTC, immanuelhume commented on src/main/java/mycelium/mycelium/commons/util/DateUtil.java
> +    public static boolean isOverdue(LocalDate date) {
perhaps `isOverdue` sounds kinda vague. since it's just comparing against today, `isBeforeToday` might be less confusing

2023-03-24 07:01 UTC, RubyNguyen07 commented on src/main/java/mycelium/mycelium/model/ModelManager.java
> +                sortedProjectList.size() >= 3 ? 3 : sortedProjectList.size()));
Ok can, i put three because our original idea was just putting 3 there.

2023-03-24 07:01 UTC, RubyNguyen07 commented on src/main/java/mycelium/mycelium/commons/util/DateUtil.java
> +    public static boolean isOverdue(LocalDate date) {
Ok that does sound better

2023-03-26 01:47 UTC, immanuelhume approved these changes
:shipit:

2023-03-26 13:58 UTC, merged