Update DeveloperGuide
AY2223S2-CS2103T-W14-1/tp pull request #44
Opened 2023-03-03 04:46 UTC by sachindavid96

Update the Developer Guide with a glossary of key terms

2023-03-03 06:26 UTC, RubyNguyen07 reviewed
Hmm I am not sure about whether we need to define project and deliverable, let's see what others think

2023-03-03 09:43 UTC, immanuelhume requested changes

2023-03-03 09:43 UTC, immanuelhume commented on docs/DeveloperGuide.md
> +* **Contact**: An individual associated with a particular project
I think we use the term "client" rather than contact right

2023-03-03 09:43 UTC, immanuelhume commented on docs/DeveloperGuide.md
> +* **Deliverable**: A task to be completed as part of a project
did we use this word somewhere so far?

2023-03-03 09:43 UTC, immanuelhume commented on docs/DeveloperGuide.md
> +* **Console-first Interface**: A text-based user interface to efficiently
I think this isn't too accurate. A "text-based" interface means something quite different from a GUI which is what we have. I think we can just define "console-first" as "an interface with interactions primarily through text commands"

2023-03-03 09:44 UTC, immanuelhume commented
If there're not many term we can think of now, can just add 1 or 2 obvious one for now. Then add more as the weeks go by

2023-03-03 15:33 UTC, sachindavid96 commented on docs/DeveloperGuide.md
> +* **Deliverable**: A task to be completed as part of a project
It was in one of the user stories

2023-03-03 15:34 UTC, sachindavid96 commented on docs/DeveloperGuide.md
> +* **Console-first Interface**: A text-based user interface to efficiently
That makes sense; will make the changes

2023-03-03 15:35 UTC, sachindavid96 commented on docs/DeveloperGuide.md
> +* **Contact**: An individual associated with a particular project
Sure

2023-03-03 15:54 UTC, sachindavid96 commented on docs/DeveloperGuide.md
> +* **Deliverable**: A task to be completed as part of a project
On second thought, I think it is quite irrelevant; will remove it

2023-03-03 16:00 UTC, sachindavid96 reviewed
I have made the requested changes, in the glossary, to the definition of the console-first interface, changed 'contact' to 'client' and removed the definition of deliverables and posting

2023-03-04 10:26 UTC, immanuelhume approved these changes
LGTM :shipit:

2023-03-04 16:01 UTC, merged