Add basic Client model with appropriate attributes
AY2223S2-CS2103T-W14-1/tp pull request #62
Opened 2023-03-07 15:46 UTC by Douglch

Closes #48.

## Changes done so far
- [x] `Client` class, adding the necessary attributes and getters.
- [x] `ClientNotFoundException` and `DuplicateClientException` for error handling.
- [x] `JsonAdaptedClient` class to convert the Jackson-friendly adapted client object into the model's `Client` object.
- [ ] Client tests
- [ ] Client List
- [ ] Client CRUD methods

2023-03-09 14:53 UTC, immanuelhume requested changes
LGTM! Just a small change required in JsonAdaptedClient

2023-03-09 14:53 UTC, immanuelhume commented on src/main/java/mycelium/mycelium/model/client/YearOfBirth.java
> +public class YearOfBirth {
Did `java.time.Year` have some issues?

2023-03-09 14:53 UTC, immanuelhume commented on src/main/java/mycelium/mycelium/storage/JsonAdaptedClient.java
> +        nullCheck(mobileNumber == null, Phone.class.getSimpleName());
These three fields can actually be null in JSON, so we must skip the null checks for them.

2023-03-09 14:53 UTC, immanuelhume commented on src/main/java/mycelium/mycelium/storage/JsonAdaptedClient.java
> +        nullCheck(mobileNumber == null, Phone.class.getSimpleName());
And do the validitycheck only if they are not null

2023-03-09 14:53 UTC, immanuelhume commented on src/test/java/mycelium/mycelium/model/client/YearOfBirthTest.java
> +    public void isValidYearOfBirth() {
nice tests :+1:

2023-03-09 14:53 UTC, immanuelhume commented on src/test/java/mycelium/mycelium/storage/JsonAdaptedClientTest.java
> +public class JsonAdaptedClientTest {
I think we should also test the serializing of the entire Client, i.e. create a client, serialize, then read it back and assert that we get the same client back. I'll just add to issue, can do next week.

2023-03-10 03:08 UTC, Douglch commented on src/main/java/mycelium/mycelium/model/client/YearOfBirth.java
> +public class YearOfBirth {
I was using it initially, but found out that Year's a static class and monad, where the of() method only accepts int, so I had to convert them somewhere in the code from String to int. But the main reason why I created the `YearOfBirth` class was coz I wanted to create the validity check, and I could just make everything stay as a String.

2023-03-10 03:11 UTC, Douglch commented on src/test/java/mycelium/mycelium/model/client/YearOfBirthTest.java
> +    public void isValidYearOfBirth() {
thx 🥵

2023-03-10 04:09 UTC, Douglch commented on src/main/java/mycelium/mycelium/storage/JsonAdaptedClient.java
> +        nullCheck(mobileNumber == null, Phone.class.getSimpleName());
done 👍

2023-03-12 23:21 UTC, Douglch commented on src/main/java/mycelium/mycelium/storage/JsonSerializableAddressBook.java
> +    public static final String MESSAGE_DUPLICATE_CLIENT = "Persons list contains duplicate client(s).";
To be edited

2023-03-13 01:52 UTC, immanuelhume approved these changes
:shipit:

2023-03-13 01:53 UTC, merged