Add Parser
AY2223S2-CS2103T-W14-1/tp pull request #75
Opened 2023-03-12 22:33 UTC by sachindavid96

Add parser's ability to parse commands of deleting / adding clients and projects

2023-03-13 01:58 UTC, immanuelhume commented on src/main/java/mycelium/mycelium/logic/commands/AddProjectCommand.java
> +            + CliSyntax.PREFIX_ACCEPTED_DATE + "1-Dec-2023"
Let's decide on the date format to use.

2023-03-13 02:06 UTC, immanuelhume commented on src/main/java/mycelium/mycelium/logic/commands/DeleteClientCommand.java
> +        List<Client> listWithTargetClient = model.getFilteredClientList().filtered(c -> c.getEmail().equals(targetEmail));
We'll add a more convenient method on Model for stuff like this

2023-03-13 02:17 UTC, immanuelhume commented on src/main/java/mycelium/mycelium/logic/parser/AddClientCommandParser.java
> +    private static boolean arePrefixesPresent(ArgumentMultimap argumentMultimap, Prefix... prefixes) {
Perhaps move this somewhere else since it's the same for all parsers

2023-03-13 02:22 UTC, immanuelhume commented on src/main/java/mycelium/mycelium/logic/parser/AddClientCommandParser.java
> +                Optional.of(ParserUtil.parsePhone(argMultimap.getValue(PREFIX_CLIENT_MOBILE_NUMBER).get()));
argMultimap.getValue(PREFIX_CLIENT_MOBILE_NUMBER).map(ParserUtil::parsePhone)

2023-03-13 02:30 UTC, immanuelhume commented on src/main/java/mycelium/mycelium/logic/parser/DeleteClientCommandParser.java
> +    public DeleteClientCommand parse(String args) throws ParseException {
Need to do the whole tokenize thing

2023-03-13 02:30 UTC, immanuelhume commented on src/main/java/mycelium/mycelium/logic/parser/DeleteProjectCommandParser.java
> +    public DeleteProjectCommand parse(String args) throws ParseException {
Ditto for the tokenize thing

2023-03-13 02:30 UTC, immanuelhume commented on src/main/java/mycelium/mycelium/logic/parser/ParserUtil.java
> +    public static String parseSource(String source) throws ParseException {
Don't need this, we can add a parseNonEmptyString method here for conveience

2023-03-13 02:34 UTC, immanuelhume reviewed
lgtm, some minor fixes needed

2023-03-14 08:20 UTC, StanleyNeoh requested changes
Overall, some of the functionality is broken / inconsistent

Cannot create projects as example and user guide date format is different from the implementation date format. 
Projects also expect -cn in user guide and example but actually takes -e in implementation

Client deletion broken for some weird reason. Seems like an issue with the UniqueList but it works perfectly fine with Projects so idk whats up that. You might want to work with @Douglch to resolve this, I suggested a temporary fix in comments.

2023-03-14 08:20 UTC, StanleyNeoh commented on src/main/java/mycelium/mycelium/logic/commands/DeleteClientCommand.java
> +public class DeleteClientCommand extends Command {
For some reason, .remove method in UniqueList.java does not work as intended. 

I did my own testing 
![image](https://user-images.githubusercontent.com/95394480/224936741-2735880e-c49d-4217-8e81-257031aa0c81.png)
from UniqueList.java

![image](https://user-images.githubusercontent.com/95394480/224936558-18ccbd04-9bbb-477c-a6f8-ee85cf9617a0.png)
after running `dc` command.

Some weird bug, should try to fix or change implementation

2023-03-14 08:20 UTC, StanleyNeoh commented on src/main/java/mycelium/mycelium/logic/commands/DeleteClientCommand.java
> +public class DeleteClientCommand extends Command {
![image](https://user-images.githubusercontent.com/95394480/224937251-e5f92122-b988-47fa-8e01-feb72a4e00ca.png)

Doing this seems to work tho, I think its the assert statement not being runned properly. Hmm, may be have to remove assert statements. Idk how AB3 got away with this

2023-03-14 08:20 UTC, StanleyNeoh commented on src/main/java/mycelium/mycelium/logic/commands/DeleteProjectCommand.java
> +        return new CommandResult(String.format(MESSAGE_DELETE_PROJECT_SUCCESS, targetProject.get()));
![image](https://user-images.githubusercontent.com/95394480/224937840-741dfd47-1a42-4d6f-bd68-f18b465db29e.png)

Same thing here, you might want to format the project properly. @immanuelhume

2023-03-14 08:29 UTC, immanuelhume commented on src/main/java/mycelium/mycelium/logic/commands/DeleteProjectCommand.java
> +        return new CommandResult(String.format(MESSAGE_DELETE_PROJECT_SUCCESS, targetProject.get()));
Moved to #87

2023-03-14 08:29 UTC, immanuelhume commented on src/main/java/mycelium/mycelium/logic/commands/AddClientCommand.java
> +    public static final String MESSAGE_SUCCESS = "New client added: %1$s";
Moved to #87

2023-03-14 08:34 UTC, immanuelhume commented on src/main/java/mycelium/mycelium/logic/commands/DeleteClientCommand.java
> +public class DeleteClientCommand extends Command {
The uniquelist is I write one, let me check

2023-03-14 08:39 UTC, immanuelhume commented on src/main/java/mycelium/mycelium/logic/commands/DeleteClientCommand.java
> +public class DeleteClientCommand extends Command {
Moved to #88

2023-03-14 09:15 UTC, sachindavid96 commented on src/main/java/mycelium/mycelium/logic/commands/AddProjectCommand.java
> +        + CliSyntax.PREFIX_CLIENT_NAME + "Alice Baker "
I'll change it to follow the user guide, tks!

2023-03-14 11:33 UTC, immanuelhume commented on docs/UserGuide.md
> +p -pn 'Mycelium Desktop' -e spiderman@gmail.com -src fiverr.com -dd 01/02/2075
If we include the `-dd` arg, perhaps it's better to add it to the description too, e.g. "from *fiverr.com*, with a deadline of *01/02/2075*. Also, it's probably better to pick a less ambiguous date, e.g. 14/03/2075.

2023-03-14 11:34 UTC, immanuelhume commented on docs/UserGuide.md
> +**Create a project** | p -pn project_name -e client_email -s status -src source -d description -ad accepted_date -dd deadline_date <br> e.g., `p -pn 'Mycelium Desktop' -e spiderman@gmail.com -src fiv
Ditto here, use a less ambiguous date.

2023-03-14 12:31 UTC, StanleyNeoh approved these changes
Looks good to me. All seems to be working

2023-03-14 12:33 UTC, merged